# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admineditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
